phone={
    'deviceName':'Redmi_5_Plus',
    'platformName':'Android',
    'platformVersion':'8.1',
    'automation':'appium',
    'appPackage':'com.baidu.searchbox',
    'appActivity':'com.baidu.searchbox.SplashActivity',
    'noReset':'True'
}